<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 1,
                'name' => 'EcoBottle | Fire Red (500ml)',
                'short_description' => 'This bottle stops 1000 plastic bottles from entering the ocean.',
                'description' => 'The double wall insulation keeps your cold drinks cold and your hot drinks hot. Designed with a dual opening function the leak proof lid gives you the option to sip from the spout and the base and provides easy access for filling, cleaning and adding ice. Our bottles are made from 90% recycled stainless steel and recycled materials and are 100% dishwasher safe - all while helping to save the ocean, every original EcoBottle funds the collection of 1000 ocean bound plastic bottles.',
                'price' => 35,
                'image' => '1716129350.Bottle - Fire Red.jpg',
                'reviews' => 5,
                'slug' => 'ecobottle-fire-red-500ml--1719956145',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'EcoBottle | Forest Green (500ml)',
                'short_description' => 'This bottle stops 1000 plastic bottles from entering the ocean.',
                'description' => 'The double wall insulation keeps your cold drinks cold and your hot drinks hot. Designed with a dual opening function the leak proof lid gives you the option to sip from the spout and the base and provides easy access for filling, cleaning and adding ice. Our bottles are made from 90% recycled stainless steel and recycled materials and are 100% dishwasher safe - all while helping to save the ocean, every original EcoBottle funds the collection of 1000 ocean bound plastic bottles.',
                'price' => 35,
                'image' => '1712430752.Bottle - Forest Green.jpg',
                'reviews' => 5,
                'slug' => 'ecobottle-forest-green-500ml--1719742568',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'EcoBottle | Obsidian Black (500ml)',
                'short_description' => 'This bottle stops 1000 plastic bottles from entering the ocean.',
                'description' => 'The double wall insulation keeps your cold drinks cold and your hot drinks hot. Designed with a dual opening function the leak proof lid gives you the option to sip from the spout and the base and provides easy access for filling, cleaning and adding ice. Our bottles are made from 90% recycled stainless steel and recycled materials and are 100% dishwasher safe - all while helping to save the ocean, every original EcoBottle funds the collection of 1000 ocean bound plastic bottles.',
                'price' => 35,
                'image' => '1712430805.Bottle - Obsidian Black.jpg',
                'reviews' => 5,
                'slug' => 'ecobottle-obsidian-black-500ml--1712430805',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'EcoBottle | Ocean Blue (500ml)',
                'short_description' => 'This bottle stops 1000 plastic bottles from entering the ocean.',
                'description' => 'The double wall insulation keeps your cold drinks cold and your hot drinks hot. Designed with a dual opening function the leak proof lid gives you the option to sip from the spout and the base and provides easy access for filling, cleaning and adding ice. Our bottles are made from 90% recycled stainless steel and recycled materials and are 100% dishwasher safe - all while helping to save the ocean, every original EcoBottle funds the collection of 1000 ocean bound plastic bottles.',
                'price' => 35,
                'image' => '1712430861.Bottle - Ocean Blue.jpg',
                'reviews' => 5,
                'slug' => 'ecobottle-ocean-blue-500ml--1712430861',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'EcoBottle | Rock Grey (500ml)',
                'short_description' => 'This bottle stops 1000 plastic bottles from entering the ocean.',
                'description' => 'The double wall insulation keeps your cold drinks cold and your hot drinks hot. Designed with a dual opening function the leak proof lid gives you the option to sip from the spout and the base and provides easy access for filling, cleaning and adding ice. Our bottles are made from 90% recycled stainless steel and recycled materials and are 100% dishwasher safe - all while helping to save the ocean, every original EcoBottle funds the collection of 1000 ocean bound plastic bottles.',
                'price' => 35,
                'image' => '1712430922.Bottle - Rock Grey.jpg',
                'reviews' => 5,
                'slug' => 'ecobottle-rock-grey-500ml--1712430922',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'EcoBottle | Sky Blue (500ml)',
                'short_description' => 'This bottle stops 1000 plastic bottles from entering the ocean.',
                'description' => 'The double wall insulation keeps your cold drinks cold and your hot drinks hot. Designed with a dual opening function the leak proof lid gives you the option to sip from the spout and the base and provides easy access for filling, cleaning and adding ice. Our bottles are made from 90% recycled stainless steel and recycled materials and are 100% dishwasher safe - all while helping to save the ocean, every original EcoBottle funds the collection of 1000 ocean bound plastic bottles.',
                'price' => 35,
                'image' => '1712430966.Bottle - Sky Blue.jpg',
                'reviews' => 5,
                'slug' => 'ecobottle-sky-blue-500ml--1712430966',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'EcoBottle | Sunshine Orange (500ml)',
                'short_description' => 'This bottle stops 1000 plastic bottles from entering the ocean.',
                'description' => 'The double wall insulation keeps your cold drinks cold and your hot drinks hot. Designed with a dual opening function the leak proof lid gives you the option to sip from the spout and the base and provides easy access for filling, cleaning and adding ice. Our bottles are made from 90% recycled stainless steel and recycled materials and are 100% dishwasher safe - all while helping to save the ocean, every original EcoBottle funds the collection of 1000 ocean bound plastic bottles.',
                'price' => 35,
                'image' => '1712430999.Bottle - Sunshine Orange.jpg',
                'reviews' => 5,
                'slug' => 'ecobottle-sunshine-orange-500ml--1712430999',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Eco Bottle | Orchid Purple (500ml)',
                'short_description' => 'This bottle stops 1000 plastic bottles from entering the ocean.',
                'description' => 'The double wall insulation keeps your cold drinks cold and your hot drinks hot. Designed with a dual opening function the leak proof lid gives you the option to sip from the spout and the base and provides easy access for filling, cleaning and adding ice. Our bottles are made from 90% recycled stainless steel and recycled materials and are 100% dishwasher safe - all while helping to save the ocean, every original EcoBottle funds the collection of 1000 ocean bound plastic bottles.',
                'price' => 35,
                'image' => '1719744753.1712430752.Bottle - Orchid Purple.jpg',
                'reviews' => 5,
                'slug' => 'eco-bottle-orchid-purple-500ml--1719744796',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Brew Flask | Obsidian Black (350ml)',
                'short_description' => 'Twist and sip. This 350ml flask features a 360° lid designed with hot drinks in mind ☕️',
                'description' => 'The Brew Flask’s top tech specs make it a front runner in the reusable Flask category. Designed to deliver on an unbeatable drinking experience on the go, the 360º leak proof lid allows you to sip from any angle, with an aromadome design that funnels the flow of the flavour to elevate the experience further. The 360 lockable lid means you can keep your Brew in your bag with the assurance that it won’t leak. Our Brew Flasks are made from 90% recycled stainless steel, double wall vacuum-insulated recycled materials and are 100% dishwasher safe – all while helping to save the ocean, every Brew funds the collection of 1000 ocean bound plastic bottles.',
                'price' => 40,
                'image' => '1719746031.Brew Flask Obsidian Black (350ml).jpg',
                'reviews' => 5,
                'slug' => 'brew-flask-obsidian-black-350ml--1719746031',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Brew Flask | Sky Blue (350ml)',
                'short_description' => 'Twist and sip. This 350ml flask features a 360° lid designed with hot drinks in mind ☕️',
                'description' => 'The Brew Flask’s top tech specs make it a front runner in the reusable Flask category. Designed to deliver on an unbeatable drinking experience on the go, the 360º leak proof lid allows you to sip from any angle, with an aromadome design that funnels the flow of the flavour to elevate the experience further. The 360 lockable lid means you can keep your Brew in your bag with the assurance that it won’t leak. Our Brew Flasks are made from 90% recycled stainless steel, double wall vacuum-insulated recycled materials and are 100% dishwasher safe – all while helping to save the ocean, every Brew funds the collection of 1000 ocean bound plastic bottles.',
                'price' => 40,
                'image' => '1719746100.Brew Flask Sky Blue (350ml).jpg',
                'reviews' => 5,
                'slug' => 'brew-flask-sky-blue-350ml--1719746100',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'Brew Flask | Ocean Blue (350ml)',
                'short_description' => 'Twist and sip. This 350ml flask features a 360° lid designed with hot drinks in mind ☕️',
                'description' => 'The Brew Flask’s top tech specs make it a front runner in the reusable Flask category. Designed to deliver on an unbeatable drinking experience on the go, the 360º leak proof lid allows you to sip from any angle, with an aromadome design that funnels the flow of the flavour to elevate the experience further. The 360 lockable lid means you can keep your Brew in your bag with the assurance that it won’t leak. Our Brew Flasks are made from 90% recycled stainless steel, double wall vacuum-insulated recycled materials and are 100% dishwasher safe – all while helping to save the ocean, every Brew funds the collection of 1000 ocean bound plastic bottles.',
                'price' => 40,
                'image' => '1719746151.Brew Flask Ocean Blue (350ml).jpg',
                'reviews' => 5,
                'slug' => 'brew-flask-ocean-blue-350ml--1719746151',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'Brew Flask | Rock Grey (350ml)',
                'short_description' => 'Twist and sip. This 350ml flask features a 360° lid designed with hot drinks in mind ☕️',
                'description' => 'The Brew Flask’s top tech specs make it a front runner in the reusable Flask category. Designed to deliver on an unbeatable drinking experience on the go, the 360º leak proof lid allows you to sip from any angle, with an aromadome design that funnels the flow of the flavour to elevate the experience further. The 360 lockable lid means you can keep your Brew in your bag with the assurance that it won’t leak. Our Brew Flasks are made from 90% recycled stainless steel, double wall vacuum-insulated recycled materials and are 100% dishwasher safe – all while helping to save the ocean, every Brew funds the collection of 1000 ocean bound plastic bottles.',
                'price' => 40,
                'image' => '1719746183.Brew Flask Rock Grey (350ml).jpg',
                'reviews' => 5,
                'slug' => 'brew-flask-rock-grey-350ml--1719746183',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'GO Bottle | Obsidian Black (500ml)',
                'short_description' => 'Flip, sip and go. The EcoBottle that\'s made for you on the move 🏃',
                'description' => 'The double wall insulation keeps your cold drinks cold and your hot drinks hot. Designed with a dual opening function the leak proof lid gives you the option to sip from the spout and the base and provides easy access for filling, cleaning and adding ice. Our bottles are made from 90% recycled stainless steel and recycled materials and are 100% dishwasher safe - all while helping to save the ocean, every EcoBottle GO funds the collection of 1000 ocean bound plastic bottles.',
                'price' => 38,
                'image' => '1719746756.GO Bottle Obsidian Black.jpg',
                'reviews' => 5,
                'slug' => 'go-bottle-obsidian-black-500ml--1719746820',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'GO Bottle | Ocean Blue (500ml)',
                'short_description' => 'Flip, sip and go. The EcoBottle that\'s made for you on the move 🏃',
                'description' => 'The double wall insulation keeps your cold drinks cold and your hot drinks hot. Designed with a dual opening function the leak proof lid gives you the option to sip from the spout and the base and provides easy access for filling, cleaning and adding ice. Our bottles are made from 90% recycled stainless steel and recycled materials and are 100% dishwasher safe - all while helping to save the ocean, every EcoBottle GO funds the collection of 1000 ocean bound plastic bottles.',
                'price' => 38,
                'image' => '1719746804.GO Bottle Ocean Blue.jpg',
                'reviews' => 5,
                'slug' => 'go-bottle-ocean-blue-500ml--1719746804',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'GO Bottle | Forest Green (500ml)',
                'short_description' => 'Flip, sip and go. The EcoBottle that\'s made for you on the move 🏃',
                'description' => 'The double wall insulation keeps your cold drinks cold and your hot drinks hot. Designed with a dual opening function the leak proof lid gives you the option to sip from the spout and the base and provides easy access for filling, cleaning and adding ice. Our bottles are made from 90% recycled stainless steel and recycled materials and are 100% dishwasher safe - all while helping to save the ocean, every EcoBottle GO funds the collection of 1000 ocean bound plastic bottles.',
                'price' => 38,
                'image' => '1719746879.GO Bottle Forest Green.jpg',
                'reviews' => 5,
                'slug' => 'go-bottle-forest-green-500ml--1719746879',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'name' => 'GO Bottle | Sky Blue (500ml)',
                'short_description' => 'Flip, sip and go. The EcoBottle that\'s made for you on the move 🏃',
                'description' => 'The double wall insulation keeps your cold drinks cold and your hot drinks hot. Designed with a dual opening function the leak proof lid gives you the option to sip from the spout and the base and provides easy access for filling, cleaning and adding ice. Our bottles are made from 90% recycled stainless steel and recycled materials and are 100% dishwasher safe - all while helping to save the ocean, every EcoBottle GO funds the collection of 1000 ocean bound plastic bottles.',
                'price' => 38,
                'image' => '1719746910.GO Bottle Sky Blue.jpg',
                'reviews' => 5,
                'slug' => 'go-bottle-sky-blue-500ml--1719746910',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'name' => 'GO Lid | Obsidian Black',
                'short_description' => 'Customise your current GO or add a GO lid to your OG! Compatible with the 500ml Original EcoBottle & GO Bottle.',
                'description' => 'Flip, Sip and GO! Featuring a flip-lid with built in silicone straw and split-control spout. Life on the GO never looked so good. Compatible with the 500ml EcoBottle.',
                'price' => 10,
                'image' => '1719747314.GO Lid Obsdian Black.jpg',
                'reviews' => 5,
                'slug' => 'go-lid-obsdian-black-1719747314',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'name' => 'GO Lid | Ocean Blue',
                'short_description' => 'Customise your current GO or add a GO lid to your OG! Compatible with the 500ml Original EcoBottle & GO Bottle.',
                'description' => 'Flip, Sip and GO! Featuring a flip-lid with built in silicone straw and split-control spout. Life on the GO never looked so good. Compatible with the 500ml EcoBottle.',
                'price' => 10,
                'image' => '1719750180.GO Lid Ocean Blue.jpg',
                'reviews' => 5,
                'slug' => 'go-lid-ocean-blue-1719750180',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'name' => 'GO Lid | Forest Green',
                'short_description' => 'Customise your current GO or add a GO lid to your OG! Compatible with the 500ml Original EcoBottle & GO Bottle.',
                'description' => 'Flip, Sip and GO! Featuring a flip-lid with built in silicone straw and split-control spout. Life on the GO never looked so good. Compatible with the 500ml EcoBottle.',
                'price' => 10,
                'image' => '1719750228.GO Lid Forest Green.jpg',
                'reviews' => 5,
                'slug' => 'go-lid-forest-green-1719750228',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'name' => 'GO Lid | Sky Blue',
                'short_description' => 'Customise your current GO or add a GO lid to your OG! Compatible with the 500ml Original EcoBottle & GO Bottle.',
                'description' => 'Flip, Sip and GO! Featuring a flip-lid with built in silicone straw and split-control spout. Life on the GO never looked so good. Compatible with the 500ml EcoBottle.',
                'price' => 10,
                'image' => '1719750265.GO Lid Only Sky Blue.jpg',
                'reviews' => 5,
                'slug' => 'go-lid-sky-blue-1719750719',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'name' => 'Brew Lid | Obsidian Black',
                'short_description' => 'Customise your current Brew or add a Brew lid to your OG! Compatible with the Brew Flask, 500ml Original EcoBottle & GO Bottle.',
                'description' => 'Make your EcoBottle barista approved. Our 360° Brew Lid lets coffee aromas circulate whilst combatting spills that often happen with other coffee cups.',
                'price' => 10,
                'image' => '1719751108.Brew Lid Obsidian Black.jpg',
                'reviews' => 5,
                'slug' => 'brew-lid-obsidian-black-1719751108',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'name' => 'Brew Lid | Ocean Blue',
                'short_description' => 'Customise your current Brew or add a Brew lid to your OG! Compatible with the Brew Flask, 500ml Original EcoBottle & GO Bottle.',
                'description' => 'Make your EcoBottle barista approved. Our 360° Brew Lid lets coffee aromas circulate whilst combatting spills that often happen with other coffee cups.',
                'price' => 10,
                'image' => '1719751143.Brew Lid Ocean Blue.jpg',
                'reviews' => 5,
                'slug' => 'brew-lid-ocean-blue-1719751143',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'name' => 'Brew Lid | Forest Green',
                'short_description' => 'Customise your current Brew or add a Brew lid to your OG! Compatible with the Brew Flask, 500ml Original EcoBottle & GO Bottle.',
                'description' => 'Make your EcoBottle barista approved. Our 360° Brew Lid lets coffee aromas circulate whilst combatting spills that often happen with other coffee cups.',
                'price' => 10,
                'image' => '1719751190.Brew Lid Forest Green.jpg',
                'reviews' => 5,
                'slug' => 'brew-lid-forest-green-1719751190',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'name' => 'Brew Lid | Sky Blue',
                'short_description' => 'Customise your current Brew or add a Brew lid to your OG! Compatible with the Brew Flask, 500ml Original EcoBottle & GO Bottle.',
                'description' => 'Make your EcoBottle barista approved. Our 360° Brew Lid lets coffee aromas circulate whilst combatting spills that often happen with other coffee cups.',
                'price' => 10,
                'image' => '1719751221.Brew Lid Sky Blue.jpg',
                'reviews' => 5,
                'slug' => 'brew-lid-sky-blue-1719751221',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'name' => 'Original Cap | Obsidian Black',
                'short_description' => 'Compatible with the 500ml Original EcoBottle & GO Bottle.',
                'description' => 'The original cap in our four core colours, inspired by our planet. Compatible with the 500ml EcoBottle or GO Bottle.',
                'price' => 5,
                'image' => '1719751525.Original Cap Obsidian Black.png',
                'reviews' => 5,
                'slug' => 'original-cap-obsidian-black-1719751525',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'name' => 'Original Cap | Ocean Blue',
                'short_description' => 'The original cap in our four core colours, inspired by our planet. Compatible with the 500ml EcoBottle or GO Bottle.',
                'description' => 'The original cap in our six core colours, inspired by our planet. Compatible with the 500ml EcoBottle or GO Bottle.',
                'price' => 5,
                'image' => '1719751564.Original Cap Ocean Blue.png',
                'reviews' => 5,
                'slug' => 'original-cap-ocean-blue-1719751564',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'name' => 'Original Cap | Forest Green',
                'short_description' => 'Compatible with the 500ml Original EcoBottle & GO Bottle.',
                'description' => 'The original cap in our six core colours, inspired by our planet. Compatible with the 500ml EcoBottle or GO Bottle.',
                'price' => 5,
                'image' => '1719751599.Original Cap Forest Green.png',
                'reviews' => 5,
                'slug' => 'original-cap-forest-green-1719751599',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'name' => 'Original Cap | Sky Blue',
                'short_description' => 'Compatible with the 500ml Original EcoBottle & GO Bottle.',
                'description' => 'The original cap in our four core colours, inspired by our planet. Compatible with the 500ml EcoBottle or GO Bottle.',
                'price' => 5,
                'image' => '1719751645.Original Cap Sky Blue.jpg',
                'reviews' => 5,
                'slug' => 'original-cap-sky-blue-1719751645',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'name' => 'Carry Loop | Obsidian Black',
                'short_description' => 'Mix and match carry loops to make your bottle your own.',
                'description' => 'We pride ourselves on making products that will last a lifetime, but sometimes things can go wrong. Don’t worry, if you ever have an issue with your product, we provide a warranty. Our 10-year repair and replacement scheme covers manufacturing defects and parts that have been accidentally broken.',
                'price' => 5,
                'image' => '1719752349.Carry Loop Obsidian Black.jpg',
                'reviews' => 5,
                'slug' => 'carry-loop-obsidian-black-1719752349',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'name' => 'Carry Loop | Ocean Blue',
                'short_description' => 'Mix and match carry loops to make your bottle your own.',
                'description' => 'We pride ourselves on making products that will last a lifetime, but sometimes things can go wrong. Don’t worry, if you ever have an issue with your product, we provide a warranty. Our 10-year repair and replacement scheme covers manufacturing defects and parts that have been accidentally broken.',
                'price' => 5,
                'image' => '1719752373.Carry Loop Ocean Blue.jpg',
                'reviews' => 5,
                'slug' => 'carry-loop-ocean-blue-1719752373',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'name' => 'Carry Loop | Forest Green',
                'short_description' => 'Mix and match carry loops to make your bottle your own.',
                'description' => 'We pride ourselves on making products that will last a lifetime, but sometimes things can go wrong. Don’t worry, if you ever have an issue with your product, we provide a warranty. Our 10-year repair and replacement scheme covers manufacturing defects and parts that have been accidentally broken.',
                'price' => 5,
                'image' => '1719752396.Carry Loop Forest Green.jpg',
                'reviews' => 5,
                'slug' => 'carry-loop-forest-green-1719752396',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'name' => 'Carry Loop | Sky Blue',
                'short_description' => 'Mix and match carry loops to make your bottle your own.',
                'description' => 'We pride ourselves on making products that will last a lifetime, but sometimes things can go wrong. Don’t worry, if you ever have an issue with your product, we provide a warranty. Our 10-year repair and replacement scheme covers manufacturing defects and parts that have been accidentally broken.',
                'price' => 5,
                'image' => '1719752419.Carry Loop Sky Blue.jpg',
                'reviews' => 5,
                'slug' => 'carry-loop-sky-blue-1719752419',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'name' => 'OG Duo',
                'short_description' => '2 x OG EcoBottles',
                'description' => 'Our bestselling original EcoBottle - one for you and one for a friend. Our award-winning EcoBottle is designed to come along, at home and beyond. It keeps your cold drinks cold and your hot drinks hot. Ice, coffee, cocktails and smoothies are all good, thanks to its double lid, dual opening that lets you sip, fill, pour and clean with joy.',
                'price' => 60,
                'image' => '1719754221.OG Duo.jpg',
                'reviews' => 5,
                'slug' => 'og-duo-1719754221',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'name' => 'Brew Duo',
                'short_description' => '2 x Brew Flasks',
                'description' => 'One for you, one for a friend. Not just for hot drinks - our barista-approved brew flasks are the perfect iced coffee companion. Unlike other cups, they won\'t leak or sweat in your bag and are 100% dishwasher safe. Our double wall vacuum insulation means your ice will stay solid all day, and the 360° lid lets you take in all those sweet coffee aromas with every sip. All that while helping to save the ocean too, with every sale funding the collection of 11.4kg of ocean-bound plastic, equivalent to 1000 plastic bottles.',
                'price' => 60,
                'image' => '1719754269.Brew Duo.jpg',
                'reviews' => 5,
                'slug' => 'brew-duo-1719754269',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'name' => 'GO Duo',
                'short_description' => '2 x GO Bottles',
                'description' => 'One for you, one for a friend. This 500ml bottle features a flip-lid with built in silicone straw and split-control spout. Life on the GO never looked so good.',
                'price' => 64,
                'image' => '1719754304.GO Duo.jpg',
                'reviews' => 5,
                'slug' => 'go-duo-1719754304',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'name' => 'The Whole Family',
                'short_description' => 'OG EcoBottle + Big EcoBottle + Brew Flask + GO Bottle',
                'description' => 'Be prepared for any occasion with the entire EcoBottle range. Whether at work, getting coffee, or on the go, The Whole Family has you covered.',
                'price' => 120,
                'image' => '1719754343.The Whole Family.jpg',
                'reviews' => 5,
                'slug' => 'the-whole-family-1719756178',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'name' => 'Travel Mug (350ml)',
                'short_description' => 'The Travel Mug will give you that familiar, feel-good drinking experience whether you’re inside or out.',
                'description' => 'The vacuum-sealed double-wall insulation and a push-fit lid keeps your cold drinks cold and your hot drinks hot. It\'s a great option for a cuppa at home, and further afield! Whether you want a hot coffee for your morning commute or simply want the convenience of a thermal mug to sit on your desk keeping your favourite beverages at the perfect temperature. The removable lid enables you to sip drinks on the move with minimal splashes or use it like a regular mug. The ergonomic handle allows you to attach it to bags/ leads/ buggies when out and about to optimise storage space and carrying capacity. Our full range of thermal Travel Mugs come with a sip lid slider that can be customised to suit your personal style with eight vibrant colours inspired by our Earth. It\'s a durable tea and coffee cup that directly supports sustainability projects to protect the planet. EcoBottle Travel Mugs are made from 90% recycled stainless steel and double wall vacuum-insulated recycled materials – all while helping to save the ocean; every Mug funds the collection of 1,000 ocean bound plastic bottles.',
                'price' => 25,
                'image' => '1719754801.Travel Mug (350ml).jpg',
                'reviews' => 5,
                'slug' => 'travel-mug-350ml--1719754801',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'name' => 'Tumbler (350ml)',
                'short_description' => 'The Tumbler is designed to be the one stop cup you’ll need when you’re heading out and about.',
                'description' => 'The vacuum-sealed double-wall insulation and a push-fit lid keeps your cold drinks chilled and your hot drinks hot. It fits seamlessly under most coffee makers, such as barista machines, and in your car\'s cup holder so it’s an obvious choice to be the last thing you pick up before you leave home each morning. The removable lid means you can sip drinks on the move with minimal splashes or use it like a regular cup. Keep your hot coffee at the perfect temperature whilst you\'re on the go, without resorting to disposable cups from the coffee shop. Or fill it with tea so you can enjoy a piping hot brew just the way you like it. Choose the EcoBottle insulated stainless steel Travel Tumbler as your day to day commute cup or use it at home as the perfect product to maintain a toasty temperature if you\'re the type of tea and coffee drinker who can often go extended periods between sips (no judgement from us!) It\'s robust and versatile, won\'t rust and can be personalised with a range of colours to bring vibrancy to the sip lid slider. Our Tumblers are made from 90% recycled stainless steel double wall vacuum-insulated recycled materials – all while helping to save the ocean, every Tumbler funds the collection of 1,000 ocean bound plastic bottles so as you drink you can feel the positivity knowing your purchase has helped protect our planet and its ocean.',
                'price' => 25,
                'image' => '1719754839.Tumbler (350ml).jpg',
                'reviews' => 5,
                'slug' => 'tumbler-350ml--1719754839',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
